config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    resources :users, only: [:show]
    resources :items, only: [:create, :destroy]
  end

  root to: 'shallows#index'
  get 'about', to: 'shallows#about'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items

  def admin?
    role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item saved to to-do list"
      redirect_to current_user
    else
      flash[:error] = "Item not saved to to-do list"
    end
  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item deleted from your to-do list"
      redirect_to current_user
    else
      flash[:error] = "Item was not deleted"
    end
  end

  private

  def item_params
    params.require(:item).permit(:body, :name)
  end
end

app/controllers/shallows_controller.rb
class ShallowsController < ApplicationController
  def index
    render "users/show" if current_user.present?
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @items = policy_scope(Item)
    @item = Item.new(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div>
	<%= form_for @item do |f| %>
		<%= f.text_field :body %>
		<%= f.submit %>
	<% end %>
</div>

app/views/items/_item.html.erb
<table class="table">
	<tr>
		<th colspan="3"><h1><%= current_user.name %>'s To-Do List</h3></th>
	</tr>
	<tr>
		<th><%= render "items/form" %></th>
	</tr>
	<tr>
		<th>Days Left</th>
		<th>Item</th>
		<th>Complete?</th>
	</tr>
<% @items.sort{|x,y| x.days_left <=> y.days_left}.each do |i| %>
	<tr>	
		<td class="col-md-1"><%= i.days_left %> days left</td>
		<td class="col-md-9"><%= i.body %></td>
		<td class="col-md-2" align="center"><%= link_to "", item_path(i.id), method: :delete, class: 'fa fa-thumbs-o-up' %></td>
	</tr>
<% end %>

</table>

app/views/items/create.html.erb
<h1>Update Your To-Do List</h1>

<%= render "form" %>

<% if @item.save %>
	<%= flash[notice: "To-do list updated!"] %>
	redirect_to user_path
<% else %>
	<%= flash[notice: "Item not updated."] %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <ul class="nav nav-tabs">
        <% if current_user %>
          <li><%= link_to "Blocitoff", user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Blocitoff", root_path %></li>
        <% end %>
          <li><%= link_to "About", about_path %></li>
        <div class="nav navbar-nav navbar-right">
          <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.email %>!<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                  <li><%= link_to "Change your password?", edit_user_registration_path %></li>
                </ul>
              </li>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
        </div>   
    </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>
  </div>
</body>
</html>

app/views/shallows/about.html.erb
<h1>About Blocitoff</h1>
<p>Blocitoff is a to-list web application created using Ruby on Rails.</p>
<p>It is part of the Bloc Full Stack Developer curriculum.</p>

app/views/shallows/index.html.erb
<div class="jumbotron">
	<h1>Blocitoff</h1>
	<p>Create self-destructing to-do lists</p>
	<p>
		<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> or
		<%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> today!
	</p>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<%= render "items/item" %>
	</div>
	</br>
	<div class="row">
		<%= link_to "Change your password", edit_user_registration_path %>
	</div>	
</div>